spring:
  datasource:
    url: jdbc:postgresql://127.0.0.1:5433/userDB
    username: postgres
    password: password
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: create-drop
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    properties:
      hibernate:
        show_sql: true
        format_sql: true

management:
  tracing:
    sampling:
      probability: 1.0

logstash:
  host: localhost
  port: 5000
  service:
    name: user-service
  log:
    level: info

# Flyway
# flyway:
#   url: jdbc:postgresql://127.0.0.1:5433/userDB
#   user: postgres
#   password: password
#   enabled: true
#   locations: classpath:db/migration
#   schemas: public

management:
  tracing:
    sampling:
      probability: 1.0

logstash:
  host: localhost
  port: 5000
  service:
    name: user-service
  log:
    level: info
